# tools — generate Nushell init files for installed third-party tools
#
# Nushell cannot `eval` shell script, so `eval "$(tool init bash)"` has no
# equivalent: tools emit a .nu file instead. This module writes those files
# into the vendor autoload dir — `$nu.data-dir/vendor/autoload`, the last
# entry of $nu.vendor-autoload-dirs — where Nushell loads them after
# config.nu and before your autoload/ drop-ins.
#
# Installation is the switch: an installed tool gets its file, an absent tool
# gets none and any stale file is deleted. Nothing is commented out. Re-run
# `nu-config tools setup` after installing or upgrading a tool, since init
# output changes between versions.
#
# vivid is not here: its output depends on the theme, so `theme use` renders it
# with everything else (modules/terminal/palette.nu). A vivid.nu this used to
# write is removed below, or it would win over the theme's LS_COLORS.

const CARAPACE_INIT = r###'# generated by `nu-config tools setup` — modules/nu-config/tools.nu says why it looks like this
$env.CARAPACE_BRIDGES = 'zsh,fish,bash,inshellisense'

# Candidates for the last of `spans` from carapace, one process per slot.
def "nu-complete carapace" [spans: list<string>]: nothing -> any {
  # The command word alone is Nushell's to complete.
  if ($spans | length) < 2 { return null }
  let partial = ($spans | last)
  let stem = (
    if ($partial =~ '[/\\]') { $partial | str replace --regex '[^/\\]*$' '' }
    else if ($partial | str contains "=") { ($partial | split row "=" | first) + "=" }
    else if ($partial | str starts-with "--") { "--" }
    else if ($partial | str starts-with "-") { "-" }
    else if ($partial | str starts-with "~") { $partial }
    else { "" }
  )
  let ask = {|last: string|
    # LENIENT: a flag carapace does not know is not the end of the line.
    let out = (with-env { CARAPACE_LENIENT: "1" } { ^carapace $spans.0 nushell ...($spans | drop 1) $last | complete })
    if $out.exit_code != 0 { "[]" } else { $out.stdout }
  }
  let read = {|json: string|
    let rows = (try { $json | from json } catch { [] })
    # An error carapace reports as a pair of candidates — `ERR` with the
    # message as its description, and `_` — is no answer; null hands the slot
    # to Nushell's file completion, [] would show nothing.
    if ($rows | is-empty) or ($rows | where {|r| ($r.display? | default "") == "ERR" } | is-not-empty) { null } else { $rows }
  }
  try { stor create -t nu_carapace_memo -c { key: str, value: str, at: int } | ignore }
  let key = ([$env.PWD] ++ ($spans | drop 1) ++ [$stem] | str join (char us) | hash md5)
  let now = (date now | into int)
  let hit = (stor open | query db "select value, at from nu_carapace_memo where key = :k" -p { k: $key })
  let json = if ($hit | is-not-empty) and (($now - $hit.0.at) < 20_000_000_000) { $hit.0.value } else {
    let fresh = (do $ask $stem)
    stor delete -t nu_carapace_memo -w $"key = '($key)'" | ignore
    { key: $key, value: $fresh, at: $now } | stor insert -t nu_carapace_memo | ignore
    $fresh
  }
  let all = (do $read $json)
  if $partial == $stem or $all == null { return $all }
  let typed = ($partial | str lowercase)
  let near = ($all | where {|c| $c.value | into string | str lowercase | str starts-with $typed })
  if ($near | is-not-empty) { $near } else { do $read (do $ask $partial) }
}

$env.config.completions.external.completer = {|place: record| nu-complete carapace $place.command }
'###

# The registry. `gen` returns the file contents and only runs when `bin` is
# on PATH. Add a tool by appending a record and running `nu-config tools setup`.
def registry []: nothing -> table {
  [
    {
      name: "zoxide"
      bin: "zoxide"
      what: "frecency cd: `z`, `zi`, PWD hook"
      gen: {|| ^zoxide init nushell }
    }
    {
      name: "atuin"
      bin: "atuin"
      what: "shell history: Ctrl+R full search, Up arrow search seeded with the current line"
      # Up arrow runs atuin with the typed text as the query ("cd" + Up shows
      # cd commands). How it matches is atuin's search_mode_shell_up_key_binding.
      gen: {|| ^atuin init nu }
    }
    {
      name: "carapace"
      bin: "carapace"
      what: "argument completions for ~1000 commands"
      # Not `carapace _carapace nushell`, which is what this wrote until
      # 2026-10-01. The snippet carapace 1.8.0 generates recomputes `scope
      # aliases`, `help commands` (twice) and `scope variables` on every Tab —
      # 43.6 ms through it against 31 ms for the bare call — takes the
      # pre-0.116 `spans`, and ends in `$env.config = $current`, a whole-record
      # assignment. What a completer needs from carapace is one line, and
      # `place.command` is the span list with aliases already expanded.
      #
      # The rest is the memo. With the Tab menu open every keystroke asks
      # again, and a menu source runs on the line editor's thread: 70-76 ms a
      # key for `docker run --n…` in a pty. So carapace is asked once per SLOT
      # — the words before the token, plus the part of the token the candidate
      # set depends on (the directory typed so far, `--flag=`, the dashes) —
      # the answer is kept for 20 s in `stor`, and what is typed narrows it
      # here: 3 ms a key. When nothing local matches, carapace is asked with
      # the token as it is, because it matches in ways a prefix test does not.
      # Self-contained on purpose: this file is loaded whether or not the
      # nu-complete module is enabled.
      gen: {|| $CARAPACE_INIT }
    }
  ]
}

# Where the generated files go.
export def "tools dir" []: nothing -> path {
  $nu.data-dir | path join vendor autoload
}

def file-for [name: string]: nothing -> path {
  tools dir | path join $"($name).nu"
}

# Installed vs generated, per tool.
export def "tools status" []: nothing -> table<tool: string, installed: bool, generated: bool, state: string, what: string> {
  registry | each {|it|
    let has_bin = (which $it.bin | is-not-empty)
    let has_file = (file-for $it.name | path exists)
    {
      tool: $it.name
      installed: $has_bin
      generated: $has_file
      state: (
        if $has_bin and $has_file { "ok" }
        else if $has_bin { "missing: run `nu-config tools setup`" }
        else if $has_file { "stale: run `nu-config tools setup`" }
        else { "not installed" }
      )
      what: $it.what
    }
  }
}

# Generate files for installed tools, remove files for absent ones. Idempotent.
export def "tools setup" [--quiet (-q)]: nothing -> nothing {
  mkdir (tools dir)
  let old_vivid = (file-for vivid)
  if ($old_vivid | path exists) { rm -f $old_vivid; print $"  (ansi yellow)removed  (ansi reset) vivid     LS_COLORS is the theme's now: `theme sync`" }
  let results = (registry | each {|it|
    let path = (file-for $it.name)
    let has_bin = (which $it.bin | is-not-empty)
    let had_file = ($path | path exists)
    if $has_bin {
      let body = (do $it.gen)
      if ($body | is-empty) {
        { tool: $it.name, action: "failed", detail: "generator produced no output" }
      } else {
        let before = if $had_file { open --raw $path } else { "" }
        $body | save -f $path
        let action = if not $had_file { "created" } else if $before == $body { "unchanged" } else { "updated" }
        { tool: $it.name, action: $action, detail: $path }
      }
    } else if $had_file {
      rm -f $path
      { tool: $it.name, action: "removed", detail: $"($it.bin) is not installed" }
    } else {
      { tool: $it.name, action: "skipped", detail: $"($it.bin) is not installed" }
    }
  })

  let shown = if $quiet { $results | where action not-in [unchanged skipped] } else { $results }
  for r in $shown {
    let colour = (match $r.action {
      "created" | "updated" => (ansi green)
      "removed" => (ansi yellow)
      "failed" => (ansi red)
      _ => (ansi dark_gray)
    })
    print $"  ($colour)($r.action | fill --width 9)(ansi reset) ($r.tool | fill --width 9) ($r.detail)"
  }
  let changed = ($results | where action in [created updated removed] | length)
  if $changed > 0 { print $"($changed) file\(s\) changed — restart Nushell to load them" }
}


def names []: nothing -> list<string> { registry | get name }

# Remove one generated file.
export def "tools remove" [tool: string@names]: nothing -> nothing {
  if $tool not-in (names) { error make { msg: $"unknown tool '($tool)'" } }
  let path = (file-for $tool)
  if ($path | path exists) { rm -f $path; print $"removed ($path)" } else { print $"($tool) has no generated file" }
}
